apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command: 
        - mongod 
        - --bind_ip_all
        - --replSet
        - rs0
        ports:
        - containerPort: 27017
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.getMongo()"
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 120
          failureThreshold: 6
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.getMongo()"
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 120
          failureThreshold: 6
        volumeMounts:
        - name: mongodb-pvc
          mountPath: /data/mongodb
      volumes:
      - name: mongodb-pvc
        persistentVolumeClaim:
          claimName: mongodb-pvc
